<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>XmlDataSource Demonstration</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:XmlDataSource ID="XmlDataSource1" runat="server" DataFile="~/App_Data/Catalog.xml" XPath="/Products/Product[UnitPrice > 10]">
        </asp:XmlDataSource>
        <asp:TreeView ID="TreeView1" runat="server" DataSourceID="XmlDataSource1" AutoGenerateDataBindings=false OnSelectedNodeChanged="TreeView1_SelectedNodeChanged">
            <DataBindings>
                <asp:TreeNodeBinding DataMember="Products" Text="All products" Value="Root" />
                <asp:TreeNodeBinding DataMember="Product" TextField="ID" FormatString="Product ID {0}"/>
                <asp:TreeNodeBinding DataMember="ProductName" TextField="#InnerText" />
                <asp:TreeNodeBinding DataMember="CategoryID" TextField="#InnerText" FormatString="Category ID {0}"/>
                <asp:TreeNodeBinding DataMember="UnitPrice" TextField="#InnerText" FormatString="${0}" />
            </DataBindings>
        </asp:TreeView>

    </div>
    </form>
</body>
</html>
